import type { Metadata } from "next";
import "../globals.css";
import SideNavBar from "@/components/SideNavBar";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
    <head>
      <link href="https://api.fontshare.com/v2/css?f[]=satoshi@300,301,400,401,500,501,700,701,900,901,1,2&display=swap" rel="stylesheet"></link>
      </head>
      <body
      className="min-h-screen w-full text-black flex"
      >
         
        <SideNavBar/>
        <div className="p-7 w-full">{children}</div>
        
        </body>
    </html>
    </ClerkProvider>
  );
}
